name: Deploy 🚀

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      # Додаємо цей крок для явного використання Node.js 24
      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm' # Пришвидшить наступні збірки завдяки кешуванню

      - name: Install 📦
        run: npm ci # Рекомендовано замість npm install для чистих серверів збірки

      - name: Build 🛠️
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
